# Generated by Django 4.1.7 on 2023-05-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_turkish',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
